import Navbar from "@/components/Navbar";
import Providers from "@/components/Providers";
import { cn } from "@/lib/utils";
import "@/styles/globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";

const generalsans = localFont({
  src: [
    // {
    //   path: "../fonts/GeneralSans-Regular.otf",
    //   style: "normal",
    // },
    {
      path: "../fonts/GeneralSans-Medium.otf",
      style: "medium",
    },
    // {
    //   path: "../fonts/GeneralSans-Bold.otf",
    //   style: "bold",
    // },
  ],
  variable: "--font-general-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={cn(generalsans.className, "font-medium")}>
      <body className={"w-full min-h-screen bg-light-90 dark:bg-dark-10"}>
        <Providers>
          <Navbar />
          {children}
        </Providers>

        {/* allow more height on mobile devices */}
        <div className="h-40 md:hidden" />
      </body>
    </html>
  );
}
