import Navbar from "@/components/Navbar";
import Providers from "@/components/Providers";
import { cn } from "@/lib/utils";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn("w-full min-h-screen bg-white", inter.className)}>
        <Providers>
          {children}
          <Navbar />
        </Providers>

        {/* allow more height on mobile devices */}
        <div className="h-40 md:hidden" />
      </body>
    </html>
  );
}
